Update Utilities.cc
Fix error when building with MinGW-w64:
```
lib/src/Utilities.cc:1226:28: error: external linkage required for symbol 'drogon::utils::internal::fixedRandomNumber' because of 'dllexport' attribute                    
```
`DROGON_EXPORT` is already specified in `lib/inc/drogon/utils/Utilities.h`, it doesn't need to be repeated in `lib/src/Utilities.cc` when defining `fixedRandomNumber`.